#!/usr/bin/env python3
"""
Godot Vita Crash Dump Analyzer
===============================
Analyzes PSVita crash dump files (.psp2dmp) generated by the Vita kernel
when a homebrew application crashes.

Based on vita-parse-core (https://github.com/xyzz/vita-parse-core)
Rewritten for Python 3 compatibility and customized for the Godot Vita project.

Requirements:
    pip install pyelftools

Usage:
    python analyze_crash.py <core_file.psp2dmp> <elf_file.elf> [options]

    Options:
        -s, --stack-size    Number of stack addresses to print (default: 32)
        --no-disasm         Skip disassembly output (if toolchain not available)
        --no-color          Disable colored output

Example:
    python analyze_crash.py ux0_data_crash.psp2dmp godot.vita.elf
"""

import gzip
import re
import struct
import subprocess
import sys
import os
import shutil
from argparse import ArgumentParser
from collections import defaultdict

try:
    from elftools.elf.elffile import ELFFile
except ImportError:
    print("ERROR: pyelftools is required. Install it with: pip install pyelftools")
    sys.exit(1)


# =============================================================================
# Color output helpers
# =============================================================================

USE_COLOR = True


def set_color(enabled):
    global USE_COLOR
    USE_COLOR = enabled


def red(s):
    return f"\033[91m{s}\033[0m" if USE_COLOR else s


def green(s):
    return f"\033[92m{s}\033[0m" if USE_COLOR else s


def yellow(s):
    return f"\033[93m{s}\033[0m" if USE_COLOR else s


def cyan(s):
    return f"\033[96m{s}\033[0m" if USE_COLOR else s


def dim(s):
    return f"\033[90m{s}\033[0m" if USE_COLOR else s


def bold(s):
    return f"\033[1m{s}\033[0m" if USE_COLOR else s


# =============================================================================
# Indented printing helpers
# =============================================================================

_indent_level = 0
_indent_width = 4


class indent:
    """Context manager for indented output."""

    def __enter__(self):
        global _indent_level
        _indent_level += _indent_width

    def __exit__(self, *args):
        global _indent_level
        _indent_level -= _indent_width


def iprint(s=""):
    """Print with current indentation level."""
    print(" " * _indent_level + str(s))


# =============================================================================
# Binary parsing helpers
# =============================================================================


def u16(buf, off):
    """Read a little-endian uint16 from buffer at offset."""
    return struct.unpack("<H", buf[off : off + 2])[0]


def u32(buf, off):
    """Read a little-endian uint32 from buffer at offset."""
    return struct.unpack("<I", buf[off : off + 4])[0]


def c_str(buf, off):
    """Read a null-terminated C string from buffer at offset."""
    out = []
    while off < len(buf):
        ch = buf[off]
        if isinstance(ch, int):
            if ch == 0:
                break
            out.append(chr(ch))
        else:
            if ch == "\0" or ch == b"\0":
                break
            out.append(ch if isinstance(ch, str) else chr(ch))
        off += 1
    return "".join(out)


# =============================================================================
# String lookup tables
# =============================================================================

STR_STOP_REASON = defaultdict(
    lambda: "Unknown",
    {
        0x00000: "No reason",
        0x30002: "Undefined instruction exception",
        0x30003: "Prefetch abort exception",
        0x30004: "Data abort exception",
        0x60080: "Division by zero",
    },
)

STR_STATUS = defaultdict(
    lambda: "Unknown",
    {
        1: "Running",
        8: "Waiting",
        16: "Not started",
    },
)

STR_ATTR = defaultdict(
    lambda: "??",
    {
        5: "RX",
        6: "RW",
    },
)

REG_NAMES = {
    13: "SP",
    14: "LR",
    15: "PC",
}


# =============================================================================
# Data structures
# =============================================================================


class VitaThread:
    """Represents a thread from the core dump."""

    def __init__(self, data):
        self.uid = u32(data, 4)
        self.name = c_str(data, 8)
        self.stop_reason = u32(data, 0x74)
        self.status = u16(data, 0x30)
        self.pc = u32(data, 0x9C)
        self.regs = None  # Assigned later

    def __str__(self):
        return f"{self.name} <0x{self.uid:x}>"


class VitaModuleSegment:
    """Represents a segment within a loaded module."""

    def __init__(self, data, num):
        self.num = num
        self.attr = u32(data, 4)
        self.start = u32(data, 8)
        self.size = u32(data, 12)
        self.align = u32(data, 16)


class VitaModule:
    """Represents a loaded module from the core dump."""

    def __init__(self, data):
        self.uid = u32(data, 4)
        self.num_segs = u32(data, 0x4C)
        self.name = c_str(data, 0x24)
        self.segments = []

    def parse_segs(self, data):
        self.segments = []
        for x in range(self.num_segs):
            sz = 0x14
            self.segments.append(VitaModuleSegment(data[sz * x : sz * (x + 1)], x + 1))

    def parse_foot(self, data):
        # ARM exception start/end (unused for now)
        pass


class VitaRegs:
    """Represents the register state of a thread."""

    def __init__(self, data):
        self.tid = u32(data, 4)
        self.gpr = []
        for x in range(16):
            self.gpr.append(u32(data, 8 + 4 * x))


class VitaAddress:
    """Represents a resolved virtual address with optional module/segment info."""

    def __init__(self, symbol, vaddr, module=None, segment=None, offset=None):
        self._symbol = symbol
        self._module = module
        self._segment = segment
        self._offset = offset
        self._vaddr = vaddr

    def is_located(self):
        return self._module and self._segment and self._offset is not None

    def print_disas_if_available(self, elf):
        if not elf or not self.is_located():
            return

        addr_to_display = self._vaddr
        if addr_to_display & 1 == 0:
            state = "ARM"
        else:
            state = "Thumb"
            addr_to_display &= ~1

        iprint()
        iprint(bold(f"DISASSEMBLY AROUND {self._symbol}: 0x{addr_to_display:x} ({state}):"))
        elf.disas_around_addr(self._offset)

    def to_string(self, elf=None):
        if self.is_located():
            output = f"{self._symbol}: 0x{self._vaddr:x} ({self._module.name}@{self._segment.num} + 0x{self._offset:x}"
            if elf and self._module.name.endswith(".elf") and self._segment.num == 1:
                a2l_result = elf.addr2line(self._offset)
                if a2l_result:
                    output += f" => {a2l_result}"
            output += ")"
        else:
            output = f"{self._symbol}: 0x{self._vaddr:x}"
        return output

    def __str__(self):
        return self.to_string()


class Segment:
    """Represents a memory segment from the core dump."""

    def __init__(self, vaddr, data):
        self.vaddr = vaddr
        self.data = data
        self.size = len(data)


# =============================================================================
# ELF Parser (for the homebrew .elf file)
# =============================================================================


class ElfParser:
    """Parses the homebrew ELF file for symbol resolution and disassembly."""

    def __init__(self, filename, no_disasm=False):
        self.filename = filename
        self.no_disasm = no_disasm
        self.rx_vaddr = -1
        self.a2l = None
        self._a2l_cache = {}
        self._a2l_abs_cache = {}

        with open(filename, "rb") as f:
            elf = ELFFile(f)
            for seg in elf.iter_segments():
                if seg["p_type"] == "PT_LOAD" and seg["p_flags"] == 5:
                    self.rx_vaddr = seg["p_vaddr"]

        # Always try to open addr2line for symbol resolution.
        # --no-disasm only skips objdump disassembly output.
        self._open_addr2line()

    def _open_addr2line(self):
        """Open a persistent addr2line subprocess for symbol resolution."""
        addr2line_bin = shutil.which("arm-vita-eabi-addr2line")
        if not addr2line_bin:
            iprint(yellow("WARNING: arm-vita-eabi-addr2line not found in PATH. Symbol resolution disabled."))
            self.a2l = None
            return

        try:
            self.a2l = subprocess.Popen(
                ["arm-vita-eabi-addr2line", "-e", self.filename, "-f", "-p", "-C"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
            )
        except FileNotFoundError:
            self.a2l = None

    def addr2line(self, addr):
        """Resolve an offset in the executable segment to a source location.
        Results are cached to avoid redundant subprocess calls for the same address.
        """
        if not self.a2l:
            return None
        if addr in self._a2l_cache:
            return self._a2l_cache[addr]
        real_addr = addr + self.rx_vaddr
        try:
            self.a2l.stdin.write(f"{hex(real_addr)}\n".encode())
            self.a2l.stdin.flush()
            out = self.a2l.stdout.readline()
            result = out.decode().strip() or None
        except (BrokenPipeError, OSError):
            result = None
        self._a2l_cache[addr] = result
        return result

    def addr2line_absolute(self, addr):
        """Resolve an absolute virtual address to a source location.
        For EXEC-type ELF files where runtime addresses match ELF addresses.
        Results are cached.
        """
        if not self.a2l:
            return None
        if addr in self._a2l_abs_cache:
            return self._a2l_abs_cache[addr]
        try:
            self.a2l.stdin.write(f"{hex(addr)}\n".encode())
            self.a2l.stdin.flush()
            out = self.a2l.stdout.readline()
            result = out.decode().strip() or None
            # Filter out unhelpful results like "?? ??:0"
            if result and "??" in result and ":0" in result:
                result = None
        except (BrokenPipeError, OSError):
            result = None
        self._a2l_abs_cache[addr] = result
        return result

    def disas_around_addr(self, addr):
        """Disassemble code around the given offset in the executable segment."""
        if self.no_disasm:
            iprint(dim("  (disassembly skipped, --no-disasm flag set)"))
            return

        objdump_bin = shutil.which("arm-vita-eabi-objdump")
        if not objdump_bin:
            iprint(yellow("  (arm-vita-eabi-objdump not found, skipping disassembly)"))
            return

        if addr & 1 != 0:
            addr &= ~1
            thumb = True
        else:
            thumb = False

        real_addr = addr + self.rx_vaddr
        start = real_addr - 0x10
        end = real_addr + 0x10

        args = [
            "arm-vita-eabi-objdump",
            "-d",
            "-S",
            f"--start-address=0x{start:x}",
            f"--stop-address=0x{end:x}",
            self.filename,
        ]
        if thumb:
            args.append("-Mforce-thumb")

        try:
            output = subprocess.check_output(args, stderr=subprocess.DEVNULL)
            lines = output.decode(errors="replace").split("\n")

            # Filter to only show disassembly section content
            keep = False
            filtered = []
            for line in lines:
                if "Disassembly of section" in line:
                    keep = True
                    continue
                if keep:
                    filtered.append(line)

            for line in filtered:
                if f"{real_addr:x}:" in line:
                    # Highlight the crash address
                    tab_idx = line.find("\t")
                    if tab_idx >= 0:
                        line = f"!!! \t{line[tab_idx:]} !!!"
                    iprint(red(line))
                else:
                    iprint(dim(line))
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            iprint(yellow(f"  (disassembly failed: {e})"))

    def close(self):
        if self.a2l:
            try:
                self.a2l.kill()
            except OSError:
                pass


# =============================================================================
# Core Dump Parser
# =============================================================================


class CoreParser:
    """Parses a PSVita core dump (.psp2dmp) file."""

    def __init__(self, filename):
        f = None
        # Detect gzip by magic bytes (\x1f\x8b) instead of relying on exceptions,
        # which is more reliable and avoids Python version differences.
        with open(filename, "rb") as probe:
            is_gzip = probe.read(2) == b"\x1f\x8b"
        if is_gzip:
            f = gzip.open(filename, "rb")
        else:
            f = open(filename, "rb")
        self.elf = ELFFile(f)

        self._file = f
        self.notes = {}
        self.segments = []
        self.modules = []
        self.threads = []
        self.tid_to_thread = {}

        self._init_notes()
        self._parse_modules()
        self._parse_threads()
        self._parse_thread_regs()

    def close(self):
        if self._file:
            self._file.close()

    def _init_notes(self):
        for seg in self.elf.iter_segments():
            if seg.header.p_type == "PT_NOTE":
                for note in seg.iter_notes():
                    self.notes[note["n_name"]] = note["n_desc"]
            elif seg.header.p_type == "PT_LOAD":
                self.segments.append(Segment(seg.header.p_vaddr, seg.data()))

    def _parse_modules(self):
        data = self.notes.get("MODULE_INFO")
        if not data:
            return

        num = u32(data, 4)
        off = 8
        for _ in range(num):
            # Module header
            sz = 0x50
            module = VitaModule(data[off : off + sz])
            off += sz
            # Module segments
            sz = module.num_segs * 0x14
            module.parse_segs(data[off : off + sz])
            off += sz
            # Module footer
            sz = 0x10
            module.parse_foot(data[off : off + sz])
            off += sz

            self.modules.append(module)

    def _parse_threads(self):
        data = self.notes.get("THREAD_INFO")
        if not data:
            return

        num = u32(data, 4)
        off = 8
        for _ in range(num):
            sz = u32(data, off)
            thread = VitaThread(data[off : off + sz])
            self.threads.append(thread)
            self.tid_to_thread[thread.uid] = thread
            off += sz

    def _parse_thread_regs(self):
        data = self.notes.get("THREAD_REG_INFO")
        if not data:
            return

        num = u32(data, 4)
        off = 8
        for _ in range(num):
            sz = u32(data, off)
            regs = VitaRegs(data[off : off + sz])
            if regs.tid in self.tid_to_thread:
                self.tid_to_thread[regs.tid].regs = regs
            off += sz

    def _build_rx_ranges(self):
        """Build a sorted list of executable (RX) memory ranges from all modules."""
        self._rx_ranges = []
        for module in self.modules:
            for segment in module.segments:
                if (segment.attr & 0xF) == 5:  # RX
                    self._rx_ranges.append((segment.start, segment.start + segment.size, module, segment))
        self._rx_ranges.sort(key=lambda r: r[0])

    def is_code_address(self, addr):
        """Check if an address falls within any executable (RX) segment.
        Returns (module, segment, offset) tuple or None.
        Thumb bit is cleared before lookup to handle Thumb function pointers.
        """
        if not hasattr(self, "_rx_ranges"):
            self._build_rx_ranges()
        addr_clean = addr & ~1
        for start, end, module, segment in self._rx_ranges:
            if start <= addr_clean < end:
                return (module, segment, addr_clean - start)
        return None

    def get_address_notation(self, symbol, vaddr):
        """Resolve a virtual address to a module/segment/offset notation."""
        for module in self.modules:
            for segment in module.segments:
                if segment.start <= vaddr < segment.start + segment.size:
                    return VitaAddress(symbol, vaddr, module, segment, vaddr - segment.start)
        return VitaAddress(symbol, vaddr)

    def read_vaddr(self, addr, size):
        """Read bytes from a virtual address in the core dump."""
        for segment in self.segments:
            if segment.vaddr <= addr < segment.vaddr + segment.size:
                off = addr - segment.vaddr
                return segment.data[off : off + size]
        return None


# =============================================================================
# Crash Log Parser (for .log files from crash_handler_vita.cpp)
# =============================================================================


class CrashLogData:
    """Parsed data from a crash log file generated by crash_handler_vita.cpp."""

    def __init__(self):
        self.crash_type = ""           # e.g. "Hardware exception - Data Abort"
        self.engine_version = ""
        self.process_uptime = ""
        self.thread_name = ""
        self.thread_id = 0
        self.thread_priority = 0
        self.thread_cpu = 0
        self.stack_size = 0
        self.stack_free = 0
        self.mem_user = 0
        self.mem_cdram = 0
        self.mem_phycont = 0
        self.regs = {}                 # register name -> int value
        self.pc = 0
        self.lr = 0
        self.sp = 0
        self.spsr = 0
        self.fsr = 0
        self.far = 0
        self.fault_type = ""           # decoded FSR string
        self.backtrace_addrs = []      # list of (label, addr) tuples
        self.stack_scan_addrs = []     # list of (label, addr) tuples from stack scanning
        self.is_signal_crash = False   # True if signal-based, False if hw exception
        self.signal_num = 0
        self.signal_name = ""


def parse_crash_log(filename):
    """Parse a crash log file (.log) generated by crash_handler_vita.cpp.

    Returns a CrashLogData object with all extracted fields.
    """
    data = CrashLogData()

    with open(filename, "r") as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()

        # Crash type header
        m = re.match(r"CRASH:\s*Hardware exception\s*-\s*(.+)", line)
        if m:
            data.crash_type = f"Hardware exception - {m.group(1)}"
            data.is_signal_crash = False
            continue

        m = re.match(r"CRASH:\s*Program crashed with signal\s+(\d+)\s*-\s*(.+)", line)
        if m:
            data.signal_num = int(m.group(1))
            data.signal_name = m.group(2)
            data.crash_type = f"Signal {data.signal_num} - {data.signal_name}"
            data.is_signal_crash = True
            continue

        # Engine version
        m = re.match(r"Engine version:\s*(.+)", line)
        if m:
            data.engine_version = m.group(1)
            continue

        # Process uptime
        m = re.match(r"Process uptime:\s*(.+)", line)
        if m:
            data.process_uptime = m.group(1)
            continue

        # Thread info
        m = re.match(r"Name:\s*(\S+)\s+TID:\s*(0x[0-9a-fA-F]+)\s+Priority:\s*(\d+)\s+CPU:\s*(\d+)", line)
        if m:
            data.thread_name = m.group(1)
            data.thread_id = int(m.group(2), 16)
            data.thread_priority = int(m.group(3))
            data.thread_cpu = int(m.group(4))
            continue

        m = re.match(r"Stack size:\s*(\d+)", line)
        if m:
            data.stack_size = int(m.group(1))
            continue

        m = re.match(r"Stack free:\s*(\d+)", line)
        if m:
            data.stack_free = int(m.group(1))
            continue

        # Memory info
        m = re.match(r"User RAM free:\s*(\d+)", line)
        if m:
            data.mem_user = int(m.group(1))
            continue

        m = re.match(r"CDRAM free:\s*(\d+)", line)
        if m:
            data.mem_cdram = int(m.group(1))
            continue

        m = re.match(r"Phycont free:\s*(\d+)", line)
        if m:
            data.mem_phycont = int(m.group(1))
            continue

        # Registers (multiple formats from the log)
        # Format: R0=0x... R1=0x... etc. on one line
        reg_matches = re.findall(r"(R\d+|SP|LR|PC|SPSR|FSR|FAR)=(0x[0-9a-fA-F]+)", line)
        if reg_matches:
            for name, val_str in reg_matches:
                val = int(val_str, 16)
                data.regs[name] = val
                if name == "PC":
                    data.pc = val
                elif name == "LR":
                    data.lr = val
                elif name == "SP":
                    data.sp = val
                elif name == "SPSR":
                    data.spsr = val
                elif name == "FSR":
                    data.fsr = val
                elif name == "FAR":
                    data.far = val
            continue

        # Fault type
        m = re.match(r"Fault type:\s*(.+)", line)
        if m:
            data.fault_type = m.group(1)
            continue

        # Backtrace entries: [PC] 0x..., [LR] 0x..., [ 2] 0x..., [0] [0x...]
        m = re.match(r"\[(PC|LR|\s*\d+)\]\s*(?:\[?)?(0x[0-9a-fA-F]+)", line)
        if m:
            label = m.group(1).strip()
            addr = int(m.group(2), 16)
            data.backtrace_addrs.append((label, addr))
            continue

        # Stack scan entries: [S 0] 0x..., [S 1] 0x..., etc.
        m = re.match(r"\[S\s*(\d+)\]\s*(0x[0-9a-fA-F]+)", line)
        if m:
            label = f"S{m.group(1)}"
            addr = int(m.group(2), 16)
            data.stack_scan_addrs.append((label, addr))
            continue

    return data


def _decode_fsr_python(fsr):
    """Decode ARM FSR (Fault Status Register) to human-readable string.
    Mirrors the C implementation in crash_handler_vita.cpp."""
    fs = ((fsr >> 10) & 0x1) << 4 | (fsr & 0xF)
    fsr_table = {
        0x01: "Alignment fault",
        0x02: "Debug event",
        0x03: "Access flag fault (Section)",
        0x04: "Instruction cache maintenance fault",
        0x05: "Translation fault (Section)",
        0x06: "Access flag fault (Page)",
        0x07: "Translation fault (Page)",
        0x08: "Synchronous external abort (non-translation)",
        0x09: "Domain fault (Section)",
        0x0B: "Domain fault (Page)",
        0x0C: "Synchronous external abort on translation (1st level)",
        0x0D: "Permission fault (Section)",
        0x0E: "Synchronous external abort on translation (2nd level)",
        0x0F: "Permission fault (Page)",
        0x10: "TLB conflict abort",
        0x16: "Asynchronous external abort",
        0x19: "Synchronous parity error on memory access",
        0x1C: "Synchronous parity error on translation (1st level)",
        0x1E: "Synchronous parity error on translation (2nd level)",
    }
    return fsr_table.get(fs, f"Unknown fault type (FS=0x{fs:02x})")


def _analyze_fault_cause(data):
    """Heuristic analysis of the crash cause based on FAR, FSR, and registers."""
    causes = []

    far = data.far
    fsr = data.fsr

    # NULL pointer dereference: FAR is a small offset from 0
    if far < 0x1000:
        if far == 0:
            causes.append(f"NULL pointer dereference (FAR=0x{far:08x}, direct NULL access)")
        else:
            causes.append(
                f"NULL pointer dereference (FAR=0x{far:08x}, "
                f"accessing member at offset 0x{far:x} of a NULL object)"
            )

    # Stack overflow check: FAR near SP
    elif data.sp != 0 and abs(far - data.sp) < 0x1000:
        causes.append(f"Possible stack overflow (FAR=0x{far:08x} near SP=0x{data.sp:08x})")

    # Use-after-free / wild pointer: FAR in valid range but unmapped
    elif 0x81000000 <= far <= 0xBFFFFFFF:
        causes.append(
            f"Invalid memory access at 0x{far:08x} "
            f"(possible use-after-free or dangling pointer)"
        )
    else:
        causes.append(f"Invalid memory access at FAR=0x{far:08x}")

    # Check for NULL registers that might indicate the source
    null_regs = [name for name in ["R0", "R1", "R2", "R3"] if data.regs.get(name, -1) == 0]
    if null_regs:
        causes.append(f"Registers with NULL value: {', '.join(null_regs)}")

    # Memory warnings
    if data.mem_user > 0 and data.mem_user < 1024 * 1024:
        causes.append(f"WARNING: User RAM critically low ({data.mem_user} bytes free)")

    return causes


def analyze_log(log_data, elf):
    """Perform detailed analysis of a parsed crash log."""

    # Header
    iprint(red(bold("=" * 72)))
    iprint(red(bold(f"  CRASH: {log_data.crash_type}")))
    iprint(red(bold("=" * 72)))
    iprint()

    # Basic info
    iprint(bold("CRASH INFO:"))
    with indent():
        iprint(f"Type:    {log_data.crash_type}")
        if log_data.engine_version:
            iprint(f"Engine:  {log_data.engine_version}")
        if log_data.process_uptime:
            iprint(f"Uptime:  {log_data.process_uptime}")
        if log_data.fault_type:
            iprint(f"Fault:   {red(log_data.fault_type)}")
        if log_data.far != 0 or log_data.fsr != 0:
            iprint(f"FAR:     0x{log_data.far:08x}")
            iprint(f"FSR:     0x{log_data.fsr:08x} ({_decode_fsr_python(log_data.fsr)})")
    iprint()

    # Thread info
    if log_data.thread_name:
        iprint(bold("THREAD INFO:"))
        with indent():
            iprint(f"Name:     {cyan(log_data.thread_name)}")
            iprint(f"TID:      0x{log_data.thread_id:08x}")
            iprint(f"Priority: {log_data.thread_priority}")
            iprint(f"CPU:      {log_data.thread_cpu}")
            if log_data.stack_size > 0:
                iprint(f"Stack:    {log_data.stack_size} bytes (free: {log_data.stack_free} bytes)")
        iprint()

    # Memory info
    if log_data.mem_user > 0 or log_data.mem_cdram > 0:
        iprint(bold("MEMORY INFO:"))
        with indent():
            if log_data.mem_user > 0:
                mb = log_data.mem_user / (1024 * 1024)
                iprint(f"User RAM free:  {log_data.mem_user:>12} bytes ({mb:.2f} MB)")
            if log_data.mem_cdram > 0:
                mb = log_data.mem_cdram / (1024 * 1024)
                iprint(f"CDRAM free:     {log_data.mem_cdram:>12} bytes ({mb:.2f} MB)")
            if log_data.mem_phycont > 0:
                mb = log_data.mem_phycont / (1024 * 1024)
                iprint(f"Phycont free:   {log_data.mem_phycont:>12} bytes ({mb:.2f} MB)")
        iprint()

    # Registers
    iprint(bold("REGISTERS:"))
    with indent():
        # Print R0-R12 in rows of 4
        for row_start in range(0, 13, 4):
            parts = []
            for i in range(row_start, min(row_start + 4, 13)):
                name = f"R{i}"
                val = log_data.regs.get(name, None)
                if val is not None:
                    val_str = f"0x{val:08x}"
                    if val == 0:
                        val_str = red(val_str)
                    parts.append(f"{name:>3}={val_str}")
            if parts:
                iprint("  ".join(parts))
        # SP, LR, PC
        iprint(f" SP=0x{log_data.sp:08x}  LR=0x{log_data.lr:08x}  PC=0x{log_data.pc:08x}")
        if log_data.spsr:
            iprint(f"SPSR=0x{log_data.spsr:08x}")
    iprint()

    # Resolve addresses with addr2line
    iprint(bold("BACKTRACE (with symbol resolution):"))
    with indent():
        # Collect all addresses to resolve
        all_addrs = []
        for label, addr in log_data.backtrace_addrs:
            all_addrs.append((label, addr))

        if not all_addrs:
            # Fall back to PC/LR if no backtrace section
            if log_data.pc:
                all_addrs.append(("PC", log_data.pc))
            if log_data.lr:
                all_addrs.append(("LR", log_data.lr))

        if not all_addrs:
            iprint(yellow("  (no addresses to resolve)"))
        else:
            for idx, (label, addr) in enumerate(all_addrs):
                addr_clean = addr & ~1  # Clear Thumb bit
                sym_str = ""
                if elf:
                    # For EXEC-type ELF, addresses are absolute.
                    # addr2line expects the absolute address directly.
                    a2l_result = elf.addr2line_absolute(addr_clean)
                    if a2l_result:
                        sym_str = f" => {a2l_result}"

                frame_str = f"#{idx:<3} [{label:>2}] 0x{addr_clean:08x}{sym_str}"
                if label in ("PC", "LR"):
                    iprint(cyan(frame_str))
                else:
                    iprint(frame_str)

        # Also try to resolve PC/LR even if they appear in backtrace,
        # to give a clear summary
        iprint()
        iprint(bold("KEY ADDRESSES:"))
        with indent():
            for name, addr in [("PC", log_data.pc), ("LR", log_data.lr)]:
                if addr == 0:
                    continue
                addr_clean = addr & ~1
                sym_str = ""
                if elf:
                    a2l_result = elf.addr2line_absolute(addr_clean)
                    if a2l_result:
                        sym_str = f" => {a2l_result}"
                iprint(f"{name}: 0x{addr_clean:08x}{sym_str}")
    iprint()

    # Stack scan results (heuristic candidates)
    if log_data.stack_scan_addrs:
        iprint(bold("STACK SCAN (heuristic candidates, may contain false positives):"))
        iprint(dim("  These are values found on the stack that point into executable code."))
        iprint(dim("  They are likely return addresses from the call chain, but may include"))
        iprint(dim("  function pointers, vtable entries, or other code references."))
        iprint()
        with indent():
            for idx, (label, addr) in enumerate(log_data.stack_scan_addrs):
                addr_clean = addr & ~1
                sym_str = ""
                if elf:
                    a2l_result = elf.addr2line_absolute(addr_clean)
                    if a2l_result:
                        sym_str = f" => {a2l_result}"
                frame_str = f"#{idx:<3} ? 0x{addr_clean:08x}{sym_str}"
                iprint(dim(frame_str))
        iprint()

    # Heuristic cause analysis
    if not log_data.is_signal_crash:
        causes = _analyze_fault_cause(log_data)
        if causes:
            iprint(bold("PROBABLE CAUSE:"))
            with indent():
                for cause in causes:
                    iprint(red(f"• {cause}"))
            iprint()


# =============================================================================
# Main analysis logic
# =============================================================================


def print_module_info(module):
    """Print detailed information about a loaded module."""
    iprint(cyan(module.name))
    with indent():
        for segment in module.segments:
            iprint(f"Segment {segment.num}")
            with indent():
                iprint(f"Start: 0x{segment.start:x}")
                iprint(f"Size:  0x{segment.size:x} bytes")
                iprint(f"Attr:  0x{segment.attr:x} ({STR_ATTR[segment.attr & 0xF]})")
                iprint(f"Align: 0x{segment.align:x}")


def print_thread_info(core, thread, elf=None):
    """Print summary information about a thread."""
    name = thread.name
    if thread.stop_reason != 0:
        name = red(bold(name))
    else:
        name = cyan(name)

    iprint(name)
    with indent():
        iprint(f"ID: 0x{thread.uid:x}")

        reason_str = STR_STOP_REASON[thread.stop_reason]
        if thread.stop_reason != 0:
            iprint(red(f"Stop reason: 0x{thread.stop_reason:x} ({reason_str})"))
        else:
            iprint(f"Stop reason: 0x{thread.stop_reason:x} ({reason_str})")

        iprint(f"Status: 0x{thread.status:x} ({STR_STATUS[thread.status]})")

        pc = core.get_address_notation("PC", thread.pc)
        iprint(pc.to_string(elf))
        if not pc.is_located() and thread.regs:
            lr = core.get_address_notation("LR", thread.regs.gpr[14])
            iprint(lr.to_string(elf))


# Matches compiler-generated data labels: .LC0, .LANCHOR1, etc.
# Deliberately avoids matching .Lfunc_begin / .Ltext0 which are valid code labels.
_DATA_LABEL_RE = re.compile(r"\.(LC|LANCHOR)\d+")


def _is_likely_return_addr(offset, elf):
    """Heuristic check: is this address likely a return address (i.e. instruction
    after a BL/BLX call) rather than a data pointer or function pointer?

    We check the addr2line result to filter out obvious non-code entries like
    data labels (.LC*) and anchors (.LANCHOR*).
    """
    if not elf:
        return True  # Can't filter without addr2line, assume it's valid

    a2l_result = elf.addr2line(offset)
    if not a2l_result:
        return True  # No info, keep it

    # Filter out compiler-generated data labels (.LC0, .LANCHOR1, etc.)
    if _DATA_LABEL_RE.search(a2l_result):
        return False

    return True


def reconstruct_callstack(core, thread, elf, max_depth=32):
    """Reconstruct call stack using heuristic stack scanning.

    Strategy:
    1. Start with PC (current crash location)
    2. Add LR (direct caller return address)
    3. Scan the stack for values that point into executable (RX) segments
       These are candidate return addresses from the call chain.

    This is a heuristic approach - it may include false positives (e.g. function
    pointers stored on the stack) but provides a useful approximation when
    frame pointers are not available (common with -fomit-frame-pointer).
    """
    if not thread.regs:
        return []

    callstack = []
    seen_addrs = set()

    # Frame #0: PC (crash location)
    pc_val = thread.pc
    pc_notation = core.get_address_notation("PC", pc_val)
    callstack.append(("PC", pc_val, pc_notation, None, True))
    seen_addrs.add(pc_val & ~1)

    # Frame #1: LR (direct caller)
    lr_val = thread.regs.gpr[14]
    if lr_val != 0 and (lr_val & ~1) not in seen_addrs:
        lr_info = core.is_code_address(lr_val)
        if lr_info:
            lr_notation = core.get_address_notation("LR", lr_val)
            callstack.append(("LR", lr_val, lr_notation, None, True))
            seen_addrs.add(lr_val & ~1)

    # Scan stack for return addresses
    sp = thread.regs.gpr[13]
    # Scan a generous range of the stack (up to 512 words = 2KB)
    scan_words = 512
    for i in range(scan_words):
        if len(callstack) >= max_depth:
            break

        addr = sp + i * 4
        data = core.read_vaddr(addr, 4)
        if not data or len(data) < 4:
            continue

        val = u32(data, 0)
        if val == 0:
            continue

        # Skip if we've already seen this address
        val_clean = val & ~1
        if val_clean in seen_addrs:
            continue

        # Check if this value points to executable code
        code_info = core.is_code_address(val)
        if code_info:
            module, segment, offset = code_info
            # Filter: skip addresses that resolve to data labels (not real code)
            if not _is_likely_return_addr(offset, elf):
                continue

            notation = core.get_address_notation(f"[SP+0x{i*4:x}]", val)
            callstack.append((f"[SP+0x{i*4:x}]", val, notation, addr, False))
            seen_addrs.add(val_clean)

    return callstack


def print_callstack(core, thread, elf, max_depth=32):
    """Print reconstructed call stack for a crashed thread."""
    callstack = reconstruct_callstack(core, thread, elf, max_depth)

    if not callstack:
        iprint(yellow("  (unable to reconstruct call stack)"))
        return

    iprint(bold("CALL STACK (heuristic reconstruction):"))
    iprint(dim("  Note: Frames from stack scanning may include false positives (marked with '?')."))
    iprint(dim("  PC and LR frames are reliable. [SP+offset] frames are heuristic candidates."))
    iprint()

    with indent():
        for idx, (source, vaddr, notation, stack_addr, reliable) in enumerate(callstack):
            # Resolve symbol via addr2line if possible
            sym_str = ""
            if elf and notation.is_located() and notation._offset is not None:
                a2l_result = elf.addr2line(notation._offset)
                if a2l_result:
                    sym_str = f" => {a2l_result}"

            addr_display = vaddr & ~1
            if notation.is_located():
                loc = f"{notation._module.name}@{notation._segment.num} + 0x{notation._offset:x}"
            else:
                loc = "??"

            confidence = " " if reliable else "?"
            frame_str = f"#{idx:<3} {confidence} 0x{addr_display:08x}  {loc}{sym_str}"
            if reliable:
                prefix = f"  {source:>12}"
                iprint(f"{cyan(prefix)}  {frame_str}")
            else:
                prefix = f"  {source:>12}"
                iprint(f"{dim(prefix)}  {frame_str}")


def analyze_crash(core, thread, elf, stack_size):
    """Perform detailed analysis of a crashed thread."""
    reason_str = STR_STOP_REASON[thread.stop_reason]
    iprint(red(bold(f'=== THREAD "{thread.name}" <0x{thread.uid:x}> CRASHED ({reason_str}) ===')))

    if not thread.regs:
        iprint(yellow("  (no register data available for this thread)"))
        return

    # Disassembly around PC and LR
    pc = core.get_address_notation("PC", thread.pc)
    pc.print_disas_if_available(elf)

    lr = core.get_address_notation("LR", thread.regs.gpr[14])
    lr.print_disas_if_available(elf)

    # Reconstructed call stack
    iprint()
    print_callstack(core, thread, elf)

    # Register dump
    iprint()
    iprint(bold("REGISTERS:"))
    with indent():
        for x in range(13):
            reg = f"R{x}"
            iprint(f"{reg:>4}: 0x{thread.regs.gpr[x]:08x}")
        iprint(f"  SP: 0x{thread.regs.gpr[13]:08x}")
        iprint(f"  LR: {lr.to_string(elf)}")
        iprint(f"  PC: {pc.to_string(elf)}")

    # Stack contents
    iprint()
    iprint(bold("STACK CONTENTS AROUND SP:"))
    with indent():
        sp = thread.regs.gpr[13]
        for x in range(-16, stack_size):
            addr = 4 * x + sp
            data = core.read_vaddr(addr, 4)
            if data and len(data) == 4:
                val = u32(data, 0)
                prefix = "     "
                if addr == sp:
                    prefix = "SP =>"
                data_notation = core.get_address_notation(f"{prefix} 0x{addr:08x}", val)
                line = data_notation.to_string(elf)
                if addr == sp:
                    iprint(green(line))
                else:
                    iprint(line)


def _detect_input_type(filename):
    """Detect whether the input file is a crash log (.log) or core dump (.psp2dmp).
    Returns 'log' or 'coredump'.
    """
    ext = os.path.splitext(filename)[1].lower()
    if ext == ".log":
        return "log"
    if ext in (".psp2dmp", ".dmp"):
        return "coredump"

    # Heuristic: try reading as text to detect crash log format
    try:
        with open(filename, "r", errors="ignore") as f:
            header = f.read(512)
            if "CRASH:" in header and ("Hardware exception" in header or "Program crashed with signal" in header):
                return "log"
    except Exception:
        pass

    return "coredump"


def main_analyze_log(args):
    """Main entry point for crash log (.log) analysis mode."""

    # Print header
    iprint(bold("=" * 72))
    iprint(bold("  Godot Vita Crash Log Analyzer"))
    iprint(bold("=" * 72))
    iprint(f"  Log file:  {args.corefile}")
    iprint(f"  ELF file:  {args.elffile}")
    iprint(bold("=" * 72))
    iprint()

    # Parse crash log
    iprint(dim("Parsing crash log..."))
    log_data = parse_crash_log(args.corefile)

    # Parse ELF for symbol resolution
    elf = None
    iprint(dim("Parsing ELF file..."))
    elf = ElfParser(args.elffile, no_disasm=args.no_disasm)
    iprint()

    # Run analysis
    analyze_log(log_data, elf)

    # Disassembly around PC and LR if available
    if elf and not args.no_disasm and log_data.pc:
        # For EXEC ELF, the offset within the RX segment = addr - rx_vaddr
        if elf.rx_vaddr > 0:
            pc_offset = (log_data.pc & ~1) - elf.rx_vaddr
            if pc_offset > 0:
                iprint(bold(f"DISASSEMBLY AROUND PC (0x{log_data.pc & ~1:08x}):"))
                with indent():
                    elf.disas_around_addr(pc_offset)
                iprint()

            if log_data.lr:
                lr_offset = (log_data.lr & ~1) - elf.rx_vaddr
                if lr_offset > 0:
                    iprint(bold(f"DISASSEMBLY AROUND LR (0x{log_data.lr & ~1:08x}):"))
                    with indent():
                        elf.disas_around_addr(lr_offset)
                    iprint()

    # Cleanup
    if elf:
        elf.close()

    iprint(bold("=" * 72))
    iprint(bold("  Analysis complete."))
    iprint()
    iprint("  " + bold("Hint:") + " If symbols show '??' use arm-vita-eabi-addr2line manually:")
    iprint("    arm-vita-eabi-addr2line -e <elf> -f -C -p <address>")
    iprint()
    iprint("  " + bold("Hint:") + " Build with 'debug_symbols=yes' in SCons for better results.")
    iprint(bold("=" * 72))


def main_analyze_coredump(args):
    """Main entry point for core dump (.psp2dmp) analysis mode."""

    # Print header
    iprint(bold("=" * 72))
    iprint(bold("  Godot Vita Crash Dump Analyzer"))
    iprint(bold("=" * 72))
    iprint(f"  Core file: {args.corefile}")
    iprint(f"  ELF file:  {args.elffile}")
    iprint(bold("=" * 72))
    iprint()

    # Parse files
    iprint(dim("Parsing core dump..."))
    core = CoreParser(args.corefile)

    iprint(dim("Parsing ELF file..."))
    elf = ElfParser(args.elffile, no_disasm=args.no_disasm)

    # Show loaded modules if requested
    if args.show_modules:
        iprint()
        iprint(bold("=== LOADED MODULES ==="))
        with indent():
            for module in core.modules:
                print_module_info(module)
        iprint()

    # Show all threads
    iprint()
    iprint(bold("=== THREADS ==="))
    crashed = []
    with indent():
        for thread in core.threads:
            if thread.stop_reason != 0:
                crashed.append(thread)
            print_thread_info(core, thread, elf)
    iprint()

    # Detailed crash analysis for each crashed thread
    if not crashed:
        iprint(green("No crashed threads found in the core dump."))
    else:
        iprint(red(bold(f"Found {len(crashed)} crashed thread(s):")))
        iprint()
        for thread in crashed:
            analyze_crash(core, thread, elf, args.stacksize)
            iprint()

    # Cleanup
    elf.close()
    core.close()

    iprint(bold("=" * 72))
    iprint(bold("  Analysis complete."))
    if crashed:
        iprint()
        iprint("  " + bold("Hint:") + " If symbols show '??' use arm-vita-eabi-addr2line manually:")
        iprint("    arm-vita-eabi-addr2line -e <elf> -f -C -p <address>")
        iprint()
        iprint("  " + bold("Hint:") + " Build with 'debug_symbols=yes' in SCons for better results.")
    iprint(bold("=" * 72))


def main():
    parser = ArgumentParser(
        description="Godot Vita Crash Analyzer - Analyzes PSVita .psp2dmp core dumps and .log crash logs",
        epilog="Examples:\n"
               "  python analyze_crash.py crash.psp2dmp godot.vita.elf\n"
               "  python analyze_crash.py crash_20260413_005400.log godot.vita.elf\n",
    )
    parser.add_argument(
        "corefile",
        help="Path to the .psp2dmp core dump file or .log crash log file",
    )
    parser.add_argument(
        "elffile",
        help="Path to the .elf file (not .velf, not eboot.bin). Build with -g for best results.",
    )
    parser.add_argument(
        "-s",
        "--stack-size",
        dest="stacksize",
        type=int,
        default=32,
        metavar="N",
        help="Number of stack addresses to print after SP (default: 32)",
    )
    parser.add_argument(
        "--no-disasm",
        action="store_true",
        help="Skip disassembly output (useful if VitaSDK toolchain is not in PATH)",
    )
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable colored output",
    )
    parser.add_argument(
        "--show-modules",
        action="store_true",
        help="Show loaded modules information (core dump mode only)",
    )

    args = parser.parse_args()

    if args.no_color:
        set_color(False)

    # Validate input files
    if not os.path.isfile(args.corefile):
        print(red(f"ERROR: Input file not found: {args.corefile}"))
        sys.exit(1)
    if not os.path.isfile(args.elffile):
        print(red(f"ERROR: ELF file not found: {args.elffile}"))
        sys.exit(1)

    # Detect input type and dispatch
    input_type = _detect_input_type(args.corefile)

    if input_type == "log":
        main_analyze_log(args)
    else:
        main_analyze_coredump(args)


if __name__ == "__main__":
    main()
